site_name: Yi Zhou's Homepage
nav:
 - HomePage:   
    - 中文: index.md
    - English: index_en.md
    - 最优化算法: course/optimization.md
 - Research: research/publication.md
 - My Group: 
    - Introduction: aegroup/aegroup.md
    - Relaxed Clique: aegroup/relaxedclique.md
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
 #   - header.autohide
markdown_extensions:
  - meta
  - attr_list
  - pymdownx.emoji:
     emoji_index: !!python/name:materialx.emoji.twemoji
     emoji_generator: !!python/name:materialx.emoji.to_svg



  